
import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import './static/css/head-foot816e.css'
import './static/css/common.css'
import './static/css/dashboard-media640x767.css'
import './static/css/dashboard-media768x1024.css'
import './static/css/dashboard.css'
import './static/css/home-layout816e.css'
import PopupWrapper from "./components/PopupWrapper";
import Footer from "./components/Footer";
import Sidebar from "./components/Sidebar22";
import Footer2 from "./components/Footer2";
import SignupModal from "./components/SignupModal";
import Navbar from "./components/Navbar";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// className={`${geistSans.variable} ${geistMono.variable}`}
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 

  return (
    <html lang="en">
      <body >
        <Navbar/>
        <PopupWrapper/>
        <Sidebar/>
        <SignupModal/>
        {children}
      <Footer2/>
      </body>
    </html>
  );
}
